import jsPDF from "jspdf";

export const generateReportPDF = ({
    name,
    studentEmail,
    parentEmail,
    score,
    total,
    accuracy,
    confidence,
    risk,
    xp,
    streak,
    badge,
    recommendation
}) => {

    const pdf = new jsPDF();

    // Watermark
    pdf.setFontSize(40);
    pdf.setTextColor(230);

    pdf.text(
        "DYSLEXAID",
        35,
        160,
        {
            angle: 45
        }
    );

    pdf.setTextColor(0);

    pdf.setFontSize(20);

    pdf.text(
        "DyslexAid Assessment Report",
        20,
        20
    );

    pdf.setFontSize(11);

    pdf.text(
        `Assessment Date: ${new Date().toLocaleDateString()}`,
        20,
        30
    );

    pdf.setFontSize(14);

    pdf.text(
        "Student Information",
        20,
        50
    );

    pdf.setFontSize(11);

    pdf.text(
        `Name: ${name || "N/A"}`,
        20,
        60
    );

    pdf.text(
        `Student Email: ${studentEmail || "N/A"}`,
        20,
        70
    );

    pdf.text(
        `Parent Email: ${parentEmail || "N/A"}`,
        20,
        80
    );

    pdf.setFontSize(14);

    pdf.text(
        "Assessment Results",
        20,
        100
    );

    pdf.setFontSize(11);

    pdf.text(
        `Score: ${score}/${total}`,
        20,
        110
    );

    pdf.text(
        `Accuracy: ${accuracy}%`,
        20,
        120
    );

    pdf.text(
        `Confidence: ${confidence}%`,
        20,
        130
    );

    pdf.text(
        `Risk Level: ${risk}`,
        20,
        140
    );

    pdf.setFontSize(14);

    pdf.text(
        "Performance Metrics",
        20,
        160
    );

    pdf.setFontSize(11);

    pdf.text(
        `XP Points: ${xp}`,
        20,
        170
    );

    pdf.text(
        `Current Streak: ${streak}`,
        20,
        180
    );

    pdf.text(
        `Badge: ${badge}`,
        20,
        190
    );

    pdf.setFontSize(14);

    pdf.text(
        "AI Recommendation",
        20,
        210
    );

    pdf.setFontSize(11);

    pdf.text(
        recommendation,
        20,
        220,
        {
            maxWidth: 160
        }
    );

    pdf.setFontSize(10);

    pdf.text(
        "CONFIDENTIAL - Generated by DyslexAid",
        20,
        285
    );

    pdf.save(
        "DyslexAid_Assessment_Report.pdf"
    );
};