import jsPDF from "jspdf";

export const generateReportPDF = ({
    name,
    studentEmail,
    parentEmail,
    score,
    total,
    accuracy,
    confidence,
    risk,
    xp,
    streak,
    badge,
    recommendation
}) => {

    const pdf = new jsPDF();
    const today = new Date();

    const assessmentId =
        `DA-${today.getFullYear()}${String(
            today.getMonth() + 1
        ).padStart(2, "0")}${String(
            today.getDate()
        ).padStart(2, "0")}-${today.getHours()}${today.getMinutes()}`;

    // Watermark
    pdf.setFontSize(40);
    pdf.setTextColor(230);

    pdf.text(
        "DYSLEXAID",
        35,
        160,
        {
            angle: 45
        }
    );

    pdf.setTextColor(0);

    pdf.setFontSize(20);

    pdf.text(
        "DyslexAid Assessment Report",
        105,
        20,
        { align: "center" }
    );

    pdf.setFontSize(11);

    pdf.text(
        `Assessment Date: ${new Date().toLocaleDateString()}`,
        20,
        30
    );
    pdf.text(
        `Assessment ID: ${assessmentId}`,
        20,
        38
    );

    pdf.setFontSize(14);

    pdf.text(
        "Student Information",
        20,
        50
    );

    pdf.setFontSize(11);

    pdf.text(
        `Name: ${name || "N/A"}`,
        20,
        60
    );

    pdf.text(
        `Student Email: ${studentEmail || "N/A"}`,
        20,
        70
    );

    pdf.text(
        `Parent Email: ${parentEmail || "N/A"}`,
        20,
        80
    );

    pdf.setFontSize(14);

    pdf.text(
        "Assessment Results",
        20,
        90
    );

    pdf.setFontSize(11);

    pdf.text(
        `Score: ${score}/${total}`,
        20,
        100
    );

    pdf.text(
        `Accuracy: ${accuracy}%`,
        20,
        110
    );

    pdf.text(
        `Confidence: ${confidence}%`,
        20,
        120
    );
    pdf.setDrawColor(180);

    pdf.rect(
        18,
        124,
        85,
        12
    );
    if (risk === "Low Risk") {
        pdf.setTextColor(0, 180, 0);
    }
    else if (risk === "Moderate Risk") {
        pdf.setTextColor(255, 140, 0);
    }
    else {
        pdf.setTextColor(220, 0, 0);
    }

    pdf.text(
        `Risk Level: ${risk}`,
        20,
        130
    );

    pdf.setTextColor(0);

    pdf.setFontSize(14);

    pdf.text(
        "Performance Metrics",
        20,
        145
    );

    pdf.setFontSize(11);

    pdf.text(
        `XP Points: ${xp}`,
        20,
        155
    );

    pdf.text(
        `Current Streak: ${streak}`,
        20,
        165
    );
    const cleanBadge = badge
        ?.replace("🥇", "")
        ?.replace("🥈", "")
        ?.replace("🥉", "")
        ?.trim();
    pdf.text(
        `Badge Level: ${cleanBadge}`,
        20,
        175
    );

    pdf.setFontSize(14);

    pdf.text(
        "AI Recommendation",
        20,
        190
    );

    pdf.setFontSize(11);

    pdf.text(
        recommendation,
        20,
        200,
        {
            maxWidth: 160
        }
    );
    pdf.setFontSize(14);

    pdf.text(
        "AI Model Information",
        20,
        225
    );

    pdf.setFontSize(11);

    pdf.text(
        "Model Used: Logistic Regression",
        20,
        235
    );

    pdf.setTextColor(0, 150, 0);

    pdf.text(
        "Validation Accuracy: 98.5%",
        20,
        245
    );

    pdf.setTextColor(0);

    pdf.text(
        "Features Analysed: Voice Reading, Letter Recognition, Word Recognition",
        20,
        255,
        { maxWidth: 160 }
    );

    pdf.setFontSize(10);

    pdf.setTextColor(120);

    pdf.text(
        `Generated by DyslexAid | ${new Date().toLocaleString()}`,
        20,
        275
    );

    pdf.setTextColor(0);

    pdf.save(
        `DyslexAid_Report_${name || "Student"}.pdf`
    );
};